[package]
name = "gemway"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1"
handlebars = "4.3"

axum = "0.6"
tokio = { version = "1.26", features = ["full"] }

log = "0.4"
pretty_env_logger = "0.4"

serde = { version = "1.0", features = ["derive"] }
gmi = "0.2"
